baseURL = "https://heapcon.rs"
languageCode = "en-us"
title = "heapcon lite ⬣ lokalno izdanje heapspace konferencije"

[params]
  description = "heapcon lite je lokalno izdanje konferencije za softverske inženjere"
  cookie_consent_info_url = "/cookie-information/"

[permalinks]
  speakers = "/:sections/:title"
