baseURL = "https://heapcon.io"
languageCode = "en-us"
title = "heapcon ⬣ a new conference by heapspace"

[params]
  description = "heapcon is a regional tech conference for software engineers and tech businesses"

[permalinks]
  speakers = "/:section/:slug/:title"