baseURL = "http://heapcon.io"
languageCode = "en-us"
title = "heapcon ⬣ a new conference by heapspace"

[params]
	description = "heapcon is a new conference by your friends from heapspace from belgrade, serbia."
