---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/speakers
  label: Speakers
  create: all
  match: "**/*"
- type: directory
  path: content/talks
  label: Talks
  create: all
  match: "**/*"
- type: directory
  path: content/code-of-conduct
  label: Code of conduct
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.47.1
